# Generated by Django 3.1.5 on 2021-01-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/Book_image', verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
