# Generated by Django 3.1.5 on 2021-01-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210118_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': [('can_mark_returned', 'Set book as returned'), ('Can_view_all_borrowd_books', 'View all borrowed books')]},
        ),
    ]
